/**
 * Udodi Virtual Machine Opcodes
 *
 * These constants represent the low-level instructions generated by the compiler
 * and executed by the Virtual Machine (VM).
 *
 * Part of the compilation pipeline:
 * Lexer --> Parser --> Compiler --> VM
 */

/**
 * Evaluate an expression and produce a value.
 * Used for data bindings, computed values, and pipelines.
 */
export const OP_EVAL = 1;

/**
 * Set the result of the last OP_EVAL to a target (context property).
 * Used for two-way bindings and updating local state.
 */
export const OP_SET = 2;

/**
 * Bind an event listener with optional modifiers (e.g. .prevent, .stop, .once).
 */
export const OP_EVENT_BIND = 3;

/**
 * Human-readable names for opcodes.
 * Useful for debugging, error messages, and logging.
 *
 * @type {Record<number, string>}
 */
export const OPCODE_NAMES = {
    [OP_EVAL]: 'OP_EVAL',
    [OP_SET]: 'OP_SET',
    [OP_EVENT_BIND]: 'OP_EVENT_BIND',
};
