import {
	OP_EVAL,
	OP_SET,
	OP_EVENT_BIND
} from "./opcodes.js";

import { evaluate } from "./evaluator.js";

import {
	MOD_PREVENT,
	MOD_STOP,
	MOD_SELF,
	MOD_ENTER,
	MOD_ESC,
	MOD_SPACE,
	MOD_TAB,
	MOD_PASSIVE,
	MOD_NONPASSIVE,
	MOD_ONCE,
} from "./modifiers.js";

/**
 * Udodi Virtual Machine (VM)
 *
 * The runtime execution engine for Udodi directives.
 * It interprets instructions generated by the compiler and handles:
 * - Expression evaluation
 * - Event binding with full modifier support
 *
 * This VM is deliberately DOM-agnostic except for event listener management.
 *
 * Context is always supplied at call sites (execute / bindEvent / evaluate).
 * No constructor context is stored.
 *
 * @returns {{
 *   evaluate: Function,
 *   execute: Function,
 *   bindEvent: Function,
 *   unbindEvent: Function
 * }}
 */
export function createVM() {
	/**
	 * Registry of event listeners to prevent duplicates and enable cleanup.
	 * Uses WeakMap for automatic garbage collection when elements are removed.
	 *
	 * @type {WeakMap<Element, Map<string, Function>>}
	 * @private
	 */
	const listeners = new WeakMap();

	/**
	 * Executes an array of compiled instructions from the compiler.
	 *
	 * Supports multiple bindings in one directive (e.g. `href=... test=...`).
	 * Returns structured results for easy mapping to DOM properties/attributes.
	 *
	 * Runtime context (if provided) is used for BOTH evaluation and assignment.
	 *
	 * @param {Array<Object>} instructions - Instructions produced by `compile()`
	 * @param {Object|null} [ctx=null] - Optional runtime execution context
	 * @returns {Array<{target: string, value: *}>} Array of binding results
	 */
	function execute(instructions, ctx = null) {
		const len = instructions.length;
		if (len === 0) return [];

		const results = [];
		let lastValue;

		for (let i = 0; i < len; i++) {
			const inst = instructions[i];

			switch (inst.op) {
				case OP_EVAL:
					lastValue = evaluate(inst.expr, ctx);
					break;

				case OP_SET: {
					const target = inst.target;
					if (target === undefined) break;

					// return structured result for caller to handle actual DOM updates
					results.push({
						target,
						value: lastValue,
					});
					
					break;
				}

				case OP_EVENT_BIND:
					// handled elsewhere
					break;

				default:
					throw new Error(`Unsupported opcode: ${inst.op}`);
			}
		}

		return results;
	}

	/**
	 * Binds an event listener from a compiled OP_EVENT_BIND instruction.
	 *
	 * Supports all modifiers including `.prevent`, `.stop`, `.self`, `.once`,
	 * `.passive`, key filters, etc.
	 *
	 * @param {Element} element - The DOM element to attach the listener to
	 * @param {Object} instruction - Compiled event binding instruction
	 * @param {string} instruction.event - Event name (e.g. "click")
	 * @param {number} instruction.modifiers - Bitmask of modifiers
	 * @param {Object} instruction.expr - Compiled expression to evaluate on trigger
	 * @param {Object|null} [ctx=null] - Optional runtime execution context
	 */
	function bindEvent(element, instruction, ctx = null) {
		if (!element || instruction.op !== OP_EVENT_BIND) {
			return;
		}

		const { event, modifiers = 0, expr } = instruction;

		if (!expr) {
			console.warn(`[Udodi] Event binding for '${event}' has no expression`);
			return;
		}

		const key = `${event}:${modifiers}`;

		let map = listeners.get(element);
		if (map === undefined) {
			map = new Map();
			listeners.set(element, map);
		}

		// Prevent duplicate listeners
		if (map.has(key)) return;

		const handler = createEventHandler(element, ctx, modifiers, expr);
		const options = getEventOptions(modifiers);

		element.addEventListener(event, handler, options);
		map.set(key, handler);
	}

	/**
	 * Removes a previously bound event listener.
	 *
	 * @param {Element} element - DOM element
	 * @param {string} event - Event name
	 * @param {number} [modifiers=0] - Modifier bitmask
	 */
	function unbindEvent(element, event, modifiers = 0) {
		if (!element) return;

		const map = listeners.get(element);
		if (map === undefined) return;

		const key = `${event}:${modifiers}`;
		const handler = map.get(key);
		if (handler === undefined) return;

		element.removeEventListener(event, handler);
		map.delete(key);
	}

	/**
	 * Creates the actual event handler function with full modifier support.
	 *
	 * @private
	 * @param {Element} element - Target element
	 * @param {Object|null} [ctx] - Execution context
	 * @param {number} flags - Modifier bitmask
	 * @param {Object} expr - Expression to evaluate when triggered
	 * @returns {Function} Event handler
	 */
	function createEventHandler(element, ctx, flags, expr) {
		const isOnce = !!(flags & MOD_ONCE);

		return (event) => {
			// .self modifier
			if (flags & MOD_SELF && event.target !== element) return;

			// Key filters
			if (flags & MOD_ENTER && event.key !== "Enter") return;
			if (flags & MOD_ESC && event.key !== "Escape") return;
			if (flags & MOD_SPACE && event.key !== " ") return;
			if (flags & MOD_TAB && event.key !== "Tab") return;

			// .prevent and .stop
			if (flags & MOD_PREVENT) event.preventDefault();
			if (flags & MOD_STOP) event.stopPropagation();

			// Execute the bound expression
			evaluate(expr, ctx, event);

			// .once support - automatically clean up after first run
			if (isOnce) {
				unbindEvent(element, event.type, flags);
			}
		};
	}

	/**
	 * Determines the appropriate options object for addEventListener().
	 *
	 * @private
	 * @param {number} flags - Modifier bitmask
	 * @returns {Object|boolean} Options for addEventListener
	 */
	function getEventOptions(flags) {
		if (flags & MOD_PASSIVE) return { passive: true };
		if (flags & MOD_NONPASSIVE) return { passive: false };
		return false; // useCapture = false
	}

	return {
		evaluate,
		execute,
		bindEvent,
		unbindEvent,
	};
}
